version: '3'
services:
  server:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - pg
    ports:
      - 3001:3001
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    volumes:
      - ./src:/app/src

  pg:
    image: postgres
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mycontacts
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
